[project]
name = "bail-position-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.3"
dependencies = [
    "jinja2>=3.1.6",
    "streamlit>=1.43.2",
]
